update_summarizer/profiles/routes.py
from flask import Blueprint, render_template, flash, url_for, redirect
from flask_login import current_user, login_required
from update_summarizer import db, bcrypt

from flask import Blueprint, render_template

from update_summarizer.profiles.form import *
from update_summarizer.profiles.utils import remove_photo, save_photos


profiles = Blueprint("profiles", __name__, url_prefix="/profiles")


@profiles.route("/", methods=["GET", "POST"])
@login_required
def view_profile():
    form = ProfileInfoForm()
    if form.validate_on_submit():
        current_user.profile.first_name = form.first_name.data
        current_user.profile.last_name = form.last_name.data
        if form.profile_photo.data:
            file_path = current_user.profile.profile_photo
            if not ("/images/default/default.png" in file_path):
                remove_photo(file_path)
            photo_file = save_photos(
                form.profile_photo.data, current_user.id, "profile", 250, 250)
            current_user.profile.profile_photo = "/images/uploads/profile/" + photo_file
        db.session.commit()
        return render_template("profiles/view_profile.html", form=form)
    form.first_name.data = current_user.profile.first_name
    form.last_name.data = current_user.profile.last_name
    return render_template("profiles/view_profile.html", form=form)


@profiles.route("/remove-profile-photo")
@login_required
def remove_profile_photo():
    if not ("/images/default/default.png" in current_user.profile.profile_photo):
        remove_photo(current_user.profile.profile_photo)
        current_user.profile.profile_photo = "/images/default/default.png"
        db.session.commit()
        flash("Profile photo removed.", "success")
    else:
        flash("Cannot remove default profile photo.", "danger")
    return redirect(url_for("profiles.view_profile"))


@profiles.route("/my-plan", methods=["GET", "POST"])
@login_required
def my_plan():
    return render_template("profiles/my_plan.html")


@profiles.route("/change-password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        isMatched = bcrypt.check_password_hash(
            current_user.password, form.old_password.data)
        if not isMatched:
            flash("Old password did not matched", category="danger")
            return redirect("profiles.change_password")
        # Hashing
        hashed_password = bcrypt.generate_password_hash(
            form.new_password.data).decode("utf-8")
        current_user.password = hashed_password
        db.session.commit()
        flash("Password has been successfully changed", category="success")
        return redirect(url_for("profiles.view_profile"))
    return render_template("profiles/change-password.html", form=form)

update_summarizer/templates/profiles/change-password.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/profile/change-password.css')}}"> {% endblock %}
{% block content %}
<div class="container form-brand">
    <div class="row">
        <div class="col-xl-6 offset-xl-3 col-md-8 offset-md-2">
            <div class="text-center">
                <img src="{{ url_for('static', filename='images/default/logo.png') }}" alt="Brand Logo"
                    width="180px">
            </div>
            <div class="mt-4">
                <div class="p-4 cp-card">
                    <form method="post">
                        {{ form.hidden_tag() }}
                        <div class="mt-2">
                            {{ form.old_password.label(class="form-label mb-0 f-pass-label") }}
                            {% if form.old_password.errors %}
                            {{ form.old_password(class="form-control input-box is-invalid", id="old-password") }}
                            <div class="invalid-feedback">
                                {% for error in form.old_password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.old_password(class="form-control input-box", id="email") }}
                            {% endif %}
                        </div>
                        <div class="mt-2">
                            {{ form.new_password.label(class="form-label mb-0 f-pass-label") }}
                            {% if form.new_password.errors %}
                            {{ form.new_password(class="form-control input-box is-invalid", id="new-password") }}
                            <div class="invalid-feedback">
                                {% for error in form.new_password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.new_password(class="form-control input-box", id="email") }}
                            {% endif %}
                        </div>
                        <div class="mt-2">
                            {{ form.c_password.label(class="form-label mb-0 f-pass-label") }}
                            {% if form.c_password.errors %}
                            {{ form.c_password(class="form-control input-box is-invalid", id="c-password") }}
                            <div class="invalid-feedback">
                                {% for error in form.c_password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.c_password(class="form-control input-box", id="email") }}
                            {% endif %}
                        </div>
                        <div class="mt-2">
                            {{form.save(class="form-control cp-btn")}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

update_summarizer/templates/profiles/my_plan.html
{% extends "layout.html" %}

{% block content %}
<h2>sdf</h2>

{% endblock %}

update_summarizer/templates/profiles/view_profile.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div class="row mt-3 gx-3 mb-4">
    <div class="col-md-2">
      <img
        src="{{url_for('static', filename=current_user.profile.profile_photo)}}"
        alt="Profile_photo"
        class="profile_photo"
      />
    </div>
    <div class="col-md-10">
      <div class="d-flex">
        <div>
          <div class="mt-2">
            <label class="label-vp">Name:</label>
            <span class="element-vp"
              >{{current_user.profile.get_fullname()}}</span
            >
          </div>
          <div class="mt-2">
            <label class="label-vp">Email:</label>
            <span class="element-vp">{{current_user.email}}</span>
          </div>
          <div class="mt-2">
            <label class="label-vp">Subscription:</label>
            <span class="element-vp"
              >{{current_user.profile.subscription.subscription_status}}</span
            >
          </div>
          <div class="mt-2">
            <span>Joined Date: {{current_user.get_joindate()}}</span>
          </div>
        </div>
        <div style="margin-left: auto">
          <button
            title="Edit Profile"
            class="btn edit-btn"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal"
          >
            <i class="bx bxs-cog"></i>
          </button>
          <a
            href="{{url_for('profiles.change_password')}}"
            title="Change Password"
            class="btn change-pass-btn"
          >
            <i class="bx bxs-key"></i>
          </a>
          <br />
        </div>
      </div>
      <!-- <div class="user-summary-count col-md-10">
                <h4>Total Summary</h4>
                <div class="number">21</div>
                <a href="" class="profile-go-summary text-right" title="Generate New Summary">Create New</a>
            </div>

            <h4 class="mt-4">History</h4>
            <div class="card shadow-sm headline-text col-md-10">
                <p><b class="headline">Headline:</b>Indian, Pakistan military to discuss alleged Kashmir ceasefire
                    violation</p>
            </div> -->
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="mt-4">
        <h4 class="text-center">Total Summary</h4>
        <div class="number">2</div>
        <div style="text-align: center">
          <a href="{{ url_for('main.homepage') }}" class="profile-go-summary" title="Generate New Summary"
            >Create New</a
          >
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mx-auto">
      <h4 class="h">History</h4>
      <div class="headline-text p-2">
        <b class="headline">Headline:</b>Indian, Pakistan military to discuss
        alleged Kashmir ceasefire violation Lorem ipsum dolor sit amet
        consectetur adipisicing elit. Ut, velit.
      </div>
      <div class="headline-text p-2 mt-3">
        <b class="headline">Headline:</b>Twitter employees now replying on Elon Musk's tweets to voice their concerns
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div
          class="modal-header"
          style="background-color: #faf9f6; height: 50px"
        >
          <h1 class="modal-title ms-auto fs-5" id="exampleModalLabel">
            <b>Edit Profile</b>
          </h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <span class="label-ep">Profile Picture:</span><br />
            <div class="mt-3 text-center">
              <div class="text-center">
                <img
                  src="{{url_for('static', filename=current_user.profile.profile_photo)}}"
                  alt="Profile Photo"
                  class="profile_photo_edit"
                />
              </div>
              <div class="mt-2">
                {% if form.profile_photo.errors %}
                <div class="d-flex">
                  {{ form.profile_photo(class="form-control is-invalid",
                  id="profile_photo")}}
                  <button
                    type="button"
                    class="btn btn-danger ms-2"
                    data-bs-toggle="modal"
                    data-bs-target="#delete-profile-modal"
                  >
                    Delete
                  </button>
                  <div class="invalid-feedback">
                    {% for error in form.profile_photo.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %}
                  <div class="d-flex">
                    {{ form.profile_photo(class="form-control",
                    id="profile_photo") }}
                    <a
                      type="button"
                      class="btn btn-danger ms-2"
                      href="{{url_for('profiles.remove_profile_photo')}}"
                    >
                      Delete
                    </a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            <div class="row mt-3 px-3 pb-3">
              <div class="col">
                {{ form.first_name.label(class="form-label mb-0 reg-label") }}
                {% if form.first_name.errors %} {{
                form.first_name(class="form-control input-box is-invalid")}}
                <div class="invalid-feedback">
                  {% for error in form.first_name.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.first_name(class="form-control input-box",
                id="first_name") }} {% endif %}
              </div>
              <div class="col">
                {{ form.last_name.label(class="form-label mb-0 reg-label") }} {%
                if form.last_name.errors %} {{
                form.last_name(class="form-control input-box is-invalid")}}
                <div class="invalid-feedback">
                  {% for error in form.last_name.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.last_name(class="form-control input-box",
                id="last_name") }} {% endif %}
              </div>
            </div>
            <div
              class="modal-footer"
              style="
                background-color: #faf9f6;
                height: 50px;
                margin-bottom: 15px;
              "
            >
              <button
                type="button"
                class="close_update_profile"
                data-bs-dismiss="modal"
              >
                Close
              </button>
              {{form.save(class="update_profile")}}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>