update_summarizer/admin/routes.py
import os
from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import login_required, current_user
from update_summarizer.models import Feedback, Rating, Role
admin = Blueprint("admin", __name__)


@admin.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    if current_user.role != Role.ADMIN:
        next_page = request.args.get("next")
        response = redirect(next_page) if next_page else redirect(
            url_for('main.homepage'))
        return response
    feedbacks = Feedback.query.order_by(Feedback.created_at.desc()).all()[:4]
    ratings = Rating.query.order_by(Rating.created_at.desc()).all()[:6]
    return render_template("admin/dashboard.html", len=len, feedbacks=feedbacks, ratings=ratings)

@admin.route("/feedbacks", methods=["GET"])
@login_required
def all_feedback():
    feedbacks = Feedback.query.order_by(Feedback.created_at.desc()).all()
    return render_template("admin/feedbacks.html", len=len, feedbacks=feedbacks)

@admin.route("/ratings", methods=["GET"])
@login_required
def all_rating():
    ratings = Rating.query.order_by(Rating.created_at.desc()).all()
    return render_template("admin/ratings.html", len=len, ratings=ratings)

update_summarizer/checkout/routes.py
import os
from datetime import datetime

import stripe
from dateutil.relativedelta import relativedelta
from flask import Blueprint, flash, redirect, request, url_for
from flask_login import current_user, login_required

from update_summarizer import app, bcrypt, db
from update_summarizer.models import Profile

checkout = Blueprint("checkout", __name__, url_prefix="/checkout")

DOMAIN = f'http://localhost:{os.getenv("PORT")}/checkout'

stripe.api_key = os.getenv('STRIPE_KEY')

@login_required
@checkout.route('/silver', methods=['POST'])
def create_checkout_session_silver():
    try:
        checkout_session = stripe.checkout.Session.create(
            line_items = [
                {
                    'price': os.getenv('SILVER_PRICE_KEY'),
                    'quantity': 1
                }
            ],
            mode='subscription',
            success_url=f'{DOMAIN}/success?id={current_user.profile.id}&mode=silver',
            cancel_url=f'{DOMAIN}/cancel',
        )
    except Exception as e:
        return str(e)

    return redirect(checkout_session.url, code=303)

@login_required
@checkout.route('/gold', methods=['POST'])
def create_checkout_session_gold():
    try:
        checkout_session = stripe.checkout.Session.create(
            line_items = [
                {
                    'price': os.getenv('GOLD_PRICE_KEY'),
                    'quantity': 1
                }
            ],
            mode='subscription',
            success_url=f'{DOMAIN}/success?id={current_user.profile.id}&mode=gold',
            cancel_url=f'{DOMAIN}/cancel',
        )
    except Exception as e:
        return str(e)

    return redirect(checkout_session.url, code=303)

@login_required
@checkout.route('/platinum', methods=['POST'])
def create_checkout_session_platinum():
    try:
        checkout_session = stripe.checkout.Session.create(
            line_items = [
                {
                    'price': os.getenv('PLATINUM_PRICE_KEY'),
                    'quantity': 1
                }
            ],
            mode='subscription',
            success_url=f'{DOMAIN}/success?id={current_user.profile.id}&mode=platinum',
            cancel_url=f'{DOMAIN}/cancel',
        )
    except Exception as e:
        return str(e)

    return redirect(checkout_session.url, code=303)

@login_required
@checkout.route('/success', methods=['GET'])
def success():
    profile_id = request.args.get('id')
    mode = request.args.get('mode')

    duration = 1
    summary_left = 5

    if mode == 'gold':
        duration = 3
        summary_left = 7
    elif mode == 'platinum':
        duration = 6
        summary_left = 10

    profile = Profile.query.filter_by(id=profile_id).first()
    subscription = profile.subscription

    date_format = '%d/%m/%Y'

    now = datetime.strptime(datetime.today().strftime(date_format), date_format)
    expire_date = (now + relativedelta(months=duration)).date()

    subscription.subscription_status = mode
    subscription.exp_date = expire_date
    subscription.updated_at = datetime.utcnow()

    profile.summary_left = profile.summary_left + summary_left

    db.session.commit()
    flash(f'{mode.capitalize()} subscribed', 'success')
    return redirect(url_for('main.subscription_pack'))
    
@login_required
@checkout.route('/cancel', methods=['GET'])
def cancel():
    return redirect(url_for('main.subscription_pack'))

update_summarizer/main/routes.py
import math
import os
import string
import xml.etree.ElementTree as ET
from heapq import nlargest
from string import punctuation

import chardet
import nltk.data
import pandas as pd
import spacy
from bangla_stemmer.stemmer.stemmer import BanglaStemmer
# from bnlp import NLTKTokenizer
# from bnlp.corpus import digits, punctuations, stopwords
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from nltk import tokenize
from spacy.lang.en.stop_words import STOP_WORDS
from werkzeug.utils import secure_filename

from update_summarizer import db
from update_summarizer.main.cosine import cosine_similarity
from update_summarizer.main.utils import web_scrap_return_text

nlp = spacy.load('en_core_web_sm')

stopwords = list(STOP_WORDS)

import nltk

nltk.download("punkt")
nltk.download("stopwords")

from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize

main = Blueprint("main", __name__)

new_docs = {
    'topic': [],
    'file': [],
    'text': [],
    'cnt': []
}

docs = {
    'topic': [],
    'text': [],
    'summary': [],
}

summarized_df = pd.DataFrame(data=new_docs)
summarized_df.to_csv('summarized.csv', index=False)


topic = ''
cnt = 0
cnt2 = 0

num = 0


def remove_slash_n(s: str) -> str:
    """remove newline form a string"""
    return s.replace('\n', '')

# def get_summary_link(text):

#     bnltk = NLTKTokenizer()
#     text_sentences=bnltk.sentence_tokenize(text)
#     sentence_count = len(text_sentences)
#     wordFrequencyAllSentences = {} #dictionary to store dictionary of  sentences and wordFrequencyPerSentence
#     TFwordAllSentences = {} #dictionary to store dictionary of  sentences and TFWordPerSentence

#     for sentence in text_sentences:
#         word_list=bnltk.word_tokenize(sentence)
#         # pre-processing
#         word_list=BanglaStemmer().stem(word_list) # word stemming
#         word_list=[word for word in word_list if word not in punctuations] # removing punctuations
#         word_list=[word for word in word_list if word not in stopwords] # removing stopwords
#         word_list=[word for word in word_list if word not in digits] # removing digits
#         #calculating word frequency
#         wordFrequencyPerSentence = {} # dictionary to store word and its count
    
#     for sentence in text_sentences:
#         for word in word_list:        
#             wordFrequencyPerSentence[word]=word_list.count(word) # repeating words will just overwrite the count of words so no problem
#             #print(wordFrequencyPerSentence[word])
#             wordFrequencyAllSentences[sentence] = wordFrequencyPerSentence
#             #print(wordFrequencyAllSentences)
        
#         #calculating TF

#         TFWordPerSentence = {} # dictionary to store word and TF(word)
#         for word in word_list:        
#             TFWordPerSentence[word]=word_list.count(word) / len(word_list)
#             TFwordAllSentences[sentence] = TFWordPerSentence

#         #create a matrix of sentences and words
    
#     termFrequencyMatrix = wordFrequencyAllSentences; 
    
#     #counting word frequency in all sentences
#     allWords=bnltk.word_tokenize(text)
#     allWords=BanglaStemmer().stem(allWords) # word stemming
#     allWords=[word for word in allWords if word not in punctuations] # removing punctuations
#     allWords=[word for word in allWords if word not in stopwords] # removing stopwords
#     allWords=[word for word in allWords if word not in digits] # removing digits

#     allWords=set(allWords) # getting unique words in text

#     word_count= dict()
#     for word in allWords:
#         count=0
#         for sentence in text_sentences:
#             if(word in sentence): # check if word is present in sentence            
#                 count=count+1 # count sentene
#         word_count[word]=count

#     #calculating IDF
#     IDFwordsAllSentences = {} #dictionary to store dictionary of  sentences and IDFwordPerSentence

#     totalSentences=len(text_sentences) ## for using in formula

#     for sentence in text_sentences:
#         IDFwordPerSentence = {} # dictionary to store word and its IDF
        
#         for word in word_list:
#             if(word_count[word]==0):
#                 pass
#             else:
#                 IDFwordPerSentence[word]= math.log10(totalSentences / word_count[word]) # repeating words will just overwrite the count of words so no problem
#                 IDFwordsAllSentences[sentence] = IDFwordPerSentence

#     #calculating TF-IDF for each word in each sentence
#     TF_IFDwordAllSentences=TFwordAllSentences

#     for key1, value1 in TFwordAllSentences.items():
#             #print(key1)
#             #print(value1)
#             for key2, value2 in value1.items():
#                 TF_IFDwordAllSentences[key1][key2]=TFwordAllSentences[key1][key2] * IDFwordsAllSentences[key1][key2]
#                 #print(value2)
#                 break

#     #calculating weight of each sentence
#     weight_sentences={} # for storing weights of all sentences

#     for key1, value1 in TF_IFDwordAllSentences.items():
#         x=0 # initial score for a sentence
#         for key2, value2 in value1.items():
#             x=x+TF_IFDwordAllSentences[key1][key2] # weight of a sentence is the sum of tf_idf / length of sentence
#         weight_sentences[key1]=x / len(key1)

#     #calculating threshold
#     averageSentenceWeight = sum(list(weight_sentences.values())) / len(weight_sentences)

#     #generating summary
#     summary=''
#     for key, value in weight_sentences.items():
#         if(value > averageSentenceWeight):
#             summary=summary+key+' '
    
#     return summary


def getSummary(text):
    doc = nlp(text)
    tokens = [token.text for token in doc]

    punctuation1 = punctuation + '\n' + '\n\n'

    word_frequencies = {}
    for word in doc:
        if word.text.lower() not in stopwords:
            if word.text.lower() not in punctuation1:
                if word.text not in word_frequencies.keys():
                    word_frequencies[word.text] = 1
                else:
                    word_frequencies[word.text] += 1

    max_frequencys = max(word_frequencies.values())

    for word in word_frequencies.keys():
        word_frequencies[word] = word_frequencies[word]/max_frequencys

    sentence_tokens = [sent for sent in doc.sents]

    sentence_score = {}
    for sent in sentence_tokens:  # create a dictionary for sen tokens
        for word in doc:
            if word.text.lower() in word_frequencies.keys():
                if sent not in sentence_score.keys():
                    sentence_score[sent] = word_frequencies[word.text.lower()]
                else:
                    sentence_score[sent] += word_frequencies[word.text.lower()]

    select_length = int(len(sentence_tokens)*0.1 if num == 0 else 0.05)
    summary = nlargest(select_length, sentence_score, key=sentence_score.get)
    final_summary = [word.text for word in summary]
    summary = ' '.join(final_summary)
    return summary

df=pd.read_csv('merged2.csv')

@main.route("/summary-text", methods=["POST"])
@login_required
def summary_text():
    profile = current_user.profile
    if profile.summary_left == 0:
        flash('You have 0 summary token left. Come back tomorrow.', 'danger')
        return redirect(url_for('main.homepage'))
    
    summary=''
    if request.method=="POST":
        text = request.form['text']
        num=1
        summary=df['text'][0]

        #summary =getSummary(text)
        #print(summary)

        dff = pd.read_csv('summarized_bangla.csv')
        msg = dff['gold'][1][:150]
        profile.summary_left = profile.summary_left - 1
        db.session.commit()

    return redirect(url_for('main.summarizer', text=text))


def fileRead(file_p, topic):  # read the file and save it to csv file
    t = ''
    global cnt
    with open(file_p, 'r') as f:
        tree = ET.parse(file_p)
        try:
            headline_tag = tree.getroot().find('HEADLINE')
            headline = remove_slash_n(headline_tag.text)
        except:
            headline = None
        try:
            date_line_tag = tree.getroot().find('DATELINE')
            date_line = remove_slash_n(date_line_tag.text)
        except:
            date_line = ' '
        paragraphs = [remove_slash_n(p.text)
                      for p in tree.getroot().find('text').findall('p')]
        text = ' '.join(paragraphs)
        cnt = len(text)
        m = cosine_similarity(text)  # call the cosine similarity function
        print('Cosine Similarity :'+str(m))

        if m > 0.8:
            g = 'Similarity found'
        else:
            g = 'No Similarity found'
            t += text
            new_docs['topic'].append(topic)
            new_docs['file'].append(file_p)
            new_docs['text'].append(text)
            new_docs['cnt'].append(cnt)
            summarized_df = pd.DataFrame(data=new_docs)
            summarized_df.to_csv('summarized.csv', index=False)
    return t


# joint the text of all the files and Summarize it and save it to csv file
def getSummery2(file_p, t):
    msg = ''
    global topic
    global cnt, cnt2
    docs['topic'].append(topic)
    docs['text'].append(t)
    cnt = len(t)
    msg = getSummary(t)

    docs['summary'].append(msg)
    summarized_df_new = pd.DataFrame(data=docs)
    summarized_df_new.to_csv('summarized_new.csv', index=False)
    try:
        os.unlink(file_p)
    except Exception as e:
        print(e)
    return msg


@main.route("/", methods=["GET"])
def homepage():
    return render_template("main/homepage.html")


@main.route("/premium", methods=["GET"])
def premium():
    return render_template("main/premium.html")


@main.route("/subscription-pack", methods=["GET"])
def subscription_pack():
    return render_template("main/subscription_pack.html")


@main.route("/about-us", methods=["GET"])
def about_us():

update_summarizer/news/routes.py
import os
from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)

news = Blueprint("news", __name__)


@news.route("/english", methods=["GET"])
def english_news():
    return render_template("news/english/english-news.html")

@news.route("/details", methods=["GET"])
def english_details():
    return render_template("news/english/details.html")

@news.route("/details-2", methods=["GET"])
def english_details_2():
    return render_template("news/english/details-2.html")

@news.route("/international", methods=["GET"])
def international_english():
    return render_template("news/english/international.html")

@news.route("/sports_i_1", methods=["GET"])
def international_english_i_1():
    return render_template("news/english/details-i-1.html")

@news.route("/politics", methods=["GET"])
def politics_english():
    return render_template("news/english/politics.html")

@news.route("/entertainments", methods=["GET"])
def entertainments_english():
    return render_template("news/english/entertainments.html")

@news.route("/buisness", methods=["GET"])
def buisness_english():
    return render_template("news/english/buisness.html")

@news.route("/sports", methods=["GET"])
def sports_english():
    return render_template("news/english/sports.html")

@news.route("/sports_s_1", methods=["GET"])
def sports_english_s_1():
    return render_template("news/english/details-s-1.html")






@news.route("/বাংলা", methods=["GET"])
def bangla_news():
    return render_template("news/bangla/bangla-news.html")

@news.route("/bangla-details", methods=["GET"])
def bangla_details():
    return render_template("news/bangla/details.html")

@news.route("/bangla-details2", methods=["GET"])
def bangla_details2():
    return render_template("news/bangla/details2.html")

@news.route("/আন্তর্জাতিক", methods=["GET"])
def international_bangla():
    return render_template("news/bangla/international.html")

@news.route("/bangla-details-int-1", methods=["GET"])
def bangla_details_int_1():
    return render_template("news/bangla/details-int-1.html")

@news.route("/রাজনীতি", methods=["GET"])
def politics_bangla():
    return render_template("news/bangla/politics.html")

@news.route("/বিনোদন", methods=["GET"])
def entertainments_bangla():
    return render_template("news/bangla/entertainments.html")

@news.route("/ব্যবসা", methods=["GET"])
def buisness_bangla():
    return render_template("news/bangla/buisness.html")

@news.route("/খেলাধুলা", methods=["GET"])
def sports_bangla():
    return render_template("news/bangla/sports.html")

@news.route("/bangla-details-s-1", methods=["GET"])
def bangla_details_s_1():
    return render_template("news/bangla/details-s-1.html")

update_summarizer/templates/main/errors.html
{% extends "layout.html" %}

{% block title %} Error occured {% endblock %}

{% block content %}
<div class="container mt-1">
    <h1 class="mt-5 text-center fw-bold" style="color: crimson; font-size: 12rem;">
        {{ status }}
    </h1>
    <div class="text-center" style="font-size: 1.5rem;">
        {{ message }}
    </div>
</div>
{% endblock %}

update_summarizer/templates/main/help.html
{% extends "layout.html" %}

{% block content %}
<div class="container col-md-8 my-3">
    <div class="row">
        <h3>Using <span style="color: #006b41;">Update Summarizer</span> so easy and simple</h3>
        <p style="font-size: 20px;">Follow some steps! <i class="fa-solid fa-circle-down"></i></p>
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="https://images.template.net/wp-content/uploads/2016/05/13131635/Creating-Facebook-Business-Cover-Page-Template.jpg" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="https://images.template.net/wp-content/uploads/2016/05/13131635/Creating-Facebook-Business-Cover-Page-Template.jpg" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="https://images.template.net/wp-content/uploads/2016/05/13131635/Creating-Facebook-Business-Cover-Page-Template.jpg" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
    </div>
    <div class="row mt-5 d-flex">
        <h4>A complete video tutorial for guide and features</h4>
        <iframe class="video-tutorial" width="560" height="315" src="https://www.youtube.com/embed/fJ9rUzIMcZQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="row mt-5">
        <h4>Google Maps</h4>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3651.4129334119484!2d90.42335481493338!3d23.768305584580595!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c78bc678693d%3A0x3e87f7b866c0e38!2sEast%20West%20University!5e0!3m2!1sen!2sbd!4v1665855858210!5m2!1sen!2sbd" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>
{% endblock %}

update_summarizer/templates/main/index-b.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> -->
        <button class="navbar-toggler mb-2 btn btn-sm" style="font-size: 0.8rem;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"><i class="fa-solid fa-caret-down"></i> Topics</button>

        <div class="collapse bg-light navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.bangla_news')}}">বাংলাদেশ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.international_bangla')}}">আন্তর্জাতিক</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.politics_bangla')}}">রাজনীতি</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.entertainments_bangla')}}">বিনোদন</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.buisness_bangla')}}">ব্যবসা</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.sports_bangla')}}">খেলাধুলা</a>
                </li>
            </ul>
            <ul class="navbar-nav md-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.english_news')}}">English</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

update_summarizer/templates/main/index.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> -->
        <button class="navbar-toggler mb-2 btn btn-sm" style="font-size: 0.8rem;" type="button"
            data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"><i class="fa-solid fa-caret-down"></i>
            Topics</button>

        <div class="collapse bg-light navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                        href="{{url_for('news.english_news')}}">Bangladesh</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                        href="{{url_for('news.international_english')}}">International</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.politics_english')}}">Politics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.entertainments_english')}}">Entertainments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.buisness_english')}}">Buisness</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.sports_english')}}">Sports</a>
                </li>
            </ul>
            <ul class="navbar-nav md-auto mb-2 mb-lg-0">
                <li class="nav-item bangla">
                    <a class="nav-link active" aria-current="page" href="{{url_for('news.bangla_news')}}">বাংলা</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

update_summarizer/templates/main/subscription_pack.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/base/subscription_pack.css') }}"> {% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="a">
            <span class="text1">Purcase Any <b style="color: rgb(218, 2, 2);">Plan</b> </span>
            <span class="text2">The more you <b style="color: #006b41;">pay</b> the more you <b style="color: #006b41;">get</b></span>
          </div>
    </div>
    <div class="row gx-3">
        <div class="col">
            <div class="pack-card shadow">
                <form method="POST" action="{{ url_for('checkout.create_checkout_session_silver') }}">
                    <div class="head-silver">
                        <span class="silver-title-text ms-2">Silver</span>
                    </div>
                    <div class="margin-card mt-3">
                        <div class="silver-features">
                            <i class="icon-silver fa fa-try"></i>
                            <span style="margin-left: 6px"><b>Price: </b></span>
                            <span>150 BDT</span>
                        </div>
                        <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                        <div class="silver-features">
                            <i class="icon-silver fa-solid fa-repeat"></i>
                            <span style="margin-left: 6px"><b>Limit: </b></span>
                            <span>5 times per day</span>
                        </div>
                        <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                        <div class="silver-features">
                            <i class="icon-silver fa-regular fa-clock"></i>
                            <span style="margin-left: 6px"><b>Duration: </b></span>
                            <span>7 Days</span>
                        </div>
                        <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="purchase-now-silver-btn">Purchase Now</button>
                    </div>
                </form>
                <div class="text-muted" style="text-align: center; margin-bottom: 15px;">No credit card required</div>
            </div>
        </div>
        <div class="col">
            <div class="shadow pack-card">
                <form method="POST" action="{{ url_for('checkout.create_checkout_session_gold') }}">
                <div class="head-gold">
                    <span class="gold-title-text ms-2">Gold</span>
                </div>
                <div class="margin-card mt-3">
                    <div class="gold-features">
                        <i class="icon-gold fa fa-try"></i>
                        <span style="margin-left: 6px"><b>Price: </b></span>
                        <span>500 BDT</span>
                    </div>
                    <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                    <div class="gold-features">
                        <i class="icon-gold fa-solid fa-repeat"></i>
                        <span style="margin-left: 6px"><b>Limit: </b></span>
                        <span>7 times per day</span>
                    </div>
                    <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                    <div class="gold-features">
                        <i class="icon-gold fa-regular fa-clock"></i>
                        <span style="margin-left: 6px"><b>Duration: </b></span>
                        <span>1 month</span>
                    </div>
                    <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                </div>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="purchase-now-gold-btn">Purchase Now</button>
                </div>
            </form>
                <div class="text-muted" style="text-align: center; margin-bottom: 15px;">No credit card required</div>
            </div>
        </div>
        <div class="col">
            <div class="shadow pack-card">
                <form method="POST" action="{{ url_for('checkout.create_checkout_session_platinum') }}">
                <div class="head-platinum">
                    <span class="platinum-title-text ms-2">Platinum</span>
                </div>
                <div class="margin-card mt-3">
                    <div class="platinum-features">
                        <i class="icon-platinum fa fa-try"></i>
                        <span style="margin-left: 6px"><b>Price: </b></span>
                        <span>1000 BDT</span>
                    </div>
                    <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                    <div class="platinum-features">
                        <i class="icon-platinum fa-solid fa-repeat"></i>
                        <span style="margin-left: 6px"><b>Limit: </b></span>
                        <span>10 times per day</span>
                    </div>
                    <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                    <div class="platinum-features">
                        <i class="icon-platinum fa-regular fa-clock"></i>
                        <span style="margin-left: 6px"><b>Duration: </b></span>
                        <span>6 months</span>
                    </div>
                    <hr style="border: 0.5px solid black; margin-left: 10px; margin-right: 10px;">
                </div>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="purchase-now-platinum-btn">Purchase Now</button>
                </div>
            </form>
                <div class="text-muted" style="text-align: center; margin-bottom: 15px;">No credit card required</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}