update_summarizer/news/routes.py
import os
from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)

news = Blueprint("news", __name__)


@news.route("/english", methods=["GET"])
def english_news():
    return render_template("news/english/english-news.html")

@news.route("/details", methods=["GET"])
def english_details():
    return render_template("news/english/details.html")

@news.route("/details-2", methods=["GET"])
def english_details_2():
    return render_template("news/english/details-2.html")

@news.route("/international", methods=["GET"])
def international_english():
    return render_template("news/english/international.html")

@news.route("/sports_i_1", methods=["GET"])
def international_english_i_1():
    return render_template("news/english/details-i-1.html")

@news.route("/politics", methods=["GET"])
def politics_english():
    return render_template("news/english/politics.html")

@news.route("/entertainments", methods=["GET"])
def entertainments_english():
    return render_template("news/english/entertainments.html")

@news.route("/buisness", methods=["GET"])
def buisness_english():
    return render_template("news/english/buisness.html")

@news.route("/sports", methods=["GET"])
def sports_english():
    return render_template("news/english/sports.html")

@news.route("/sports_s_1", methods=["GET"])
def sports_english_s_1():
    return render_template("news/english/details-s-1.html")






@news.route("/বাংলা", methods=["GET"])
def bangla_news():
    return render_template("news/bangla/bangla-news.html")

@news.route("/bangla-details", methods=["GET"])
def bangla_details():
    return render_template("news/bangla/details.html")

@news.route("/bangla-details2", methods=["GET"])
def bangla_details2():
    return render_template("news/bangla/details2.html")

@news.route("/আন্তর্জাতিক", methods=["GET"])
def international_bangla():
    return render_template("news/bangla/international.html")

@news.route("/bangla-details-int-1", methods=["GET"])
def bangla_details_int_1():
    return render_template("news/bangla/details-int-1.html")

@news.route("/রাজনীতি", methods=["GET"])
def politics_bangla():
    return render_template("news/bangla/politics.html")

@news.route("/বিনোদন", methods=["GET"])
def entertainments_bangla():
    return render_template("news/bangla/entertainments.html")

@news.route("/ব্যবসা", methods=["GET"])
def buisness_bangla():
    return render_template("news/bangla/buisness.html")

@news.route("/খেলাধুলা", methods=["GET"])
def sports_bangla():
    return render_template("news/bangla/sports.html")

@news.route("/bangla-details-s-1", methods=["GET"])
def bangla_details_s_1():
    return render_template("news/bangla/details-s-1.html")

update_summarizer/templates/news/bangla/bangla-news.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/bangla/bangla-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index-b.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-xl-2 offset-md-1 mt-2">
            <h2 style="color: #006b41;">বাংলাদেশ</h2>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/b1.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">বুয়েট ছাত্র ফারদিন কীভাবে চনপাড়া বস্তিতে, উত্তর খুঁজছে পুলিশ</h4>
                <p class="text mb-0">বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ের (বুয়েট) শিক্ষার্থী ফারদিন নূর ওরফে পরশকে কারা কী কারণে হত্যা করেছে, তা এখনো জানা যায়নি। হত্যার সঙ্গে সরাসরি জড়িত কাউকে এখনো গ্রেপ্তার করতে পারেনি আইনশৃঙ্খলা রক্ষাকারী বাহিনী...</p>
                  <a href="{{url_for('news.bangla_details')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">২ ঘণ্টা আগে</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/b2.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">করোনা শনাক্তের হার ২ শতাংশের নিচে</h4>
                  <p class="text mb-0"></p>দেশে সর্বশেষ ২৪ ঘণ্টায় (গতকাল বুধবার সকাল ৮টা থেকে আজ বৃহস্পতিবার সকাল ৮টা পর্যন্ত) করোনা শনাক্ত হয়েছে ৬৯ জনের। এ সময় করোনায় কারও মৃত্যু হয়নি। আগের দিন করোনা শনাক্ত হয়েছিল ৬২ জনের। গত দিনেও কারও মৃত্যু হয়নি...</p>
                  <a href="{{url_for('news.bangla_details2')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">প্রকাশ: ১০ নভেম্বর ২০২২, ১৭: ৫৭</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">টেসলার ৪০০ কোটি ডলারের শেয়ার বেচবেন ইলন মাস্ক</h4>
                <p class="text mb-0">টুইটারের দায়িত্ব নিয়ে বিশ্বজুড়ে হইচই ফেলে দেওয়া ইলন মাস্ক টেসলার ৪০০ কোটি মার্কিন ডলারের শেয়ার বিক্রির ঘোষণা দিয়েছেন। ব্রিটিশ গণমাধ্যম বিবিসির এক প্রতিবেদনে এ তথ্য জানানো হয়েছে...</p>
                  <a href="{{url_for('news.bangla_details_int_1')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">প্রকাশ: ০৯ নভেম্বর ২০২২, ১০: ২৯</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">নিগারের ঝোড়ো ফিফটি, ফারিহার হ্যাটট্রিকে মালয়েশিয়াকে পাত্তা দিল না বাংলাদেশ</h4>
                <p class="text mb-0">ফারিহা ইসলামের সৌজন্যে মালয়েশিয়ার মেয়েদের ইনিংসের শুরুটা ভালো হয়নি। ব্যাটিং পাওয়ারপ্লেতে মাত্র ১৩ রান তুলতেই ৩ উইকেট হারান তাঁরা। ৩টিই পাওয়ারপ্লের শেষ ওভারে, টানা ৩ বলে। ফারিহার তৃতীয় ওভারের দ্বিতীয় বলটি মালয়েশিয়ার অধিনায়ক উইনিফ্রেড দুরাইসিঙ্গামের স্টাম্প ভেঙে দেয় দুর্দান্ত ইনসুইংয়ে। সুইং ছিল পরের বলেও। সেটিতেও এলবিডব্লুর শিকার নতুন ব্যাটার মাস এলিসা...</p>
                  <a href="{{url_for('news.bangla_details_s_1')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">প্রকাশ: ০৬ অক্টোবর ২০২২, ১৭: ৪৩</small></p>
            </div>
          </div>
          
        </div>
        <!-- <div class="col-md-1 col-xl-2 mt-2">
          <img src="{{ url_for('static', filename='images/news/english/ad.jpg')}}" alt="ad" />
        </div> -->
    </div>
  </div>

{% endblock %}

update_summarizer/templates/news/bangla/buisness.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/bangla/bangla-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index-b.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-md-2 mt-2">
            <h2 style="color: #006b41;">ব্যবসা</h2>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/b1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">বুয়েট ছাত্র ফারদিন কীভাবে চনপাড়া বস্তিতে, উত্তর খুঁজছে পুলিশ</h4>
                  <p class="text mb-0">বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ের (বুয়েট) শিক্ষার্থী ফারদিন নূর ওরফে পরশকে কারা কী কারণে হত্যা করেছে, তা এখনো জানা যায়নি। হত্যার সঙ্গে সরাসরি জড়িত কাউকে এখনো গ্রেপ্তার করতে পারেনি আইনশৃঙ্খলা রক্ষাকারী বাহিনী...</p>
                    <a href="{{url_for('news.bangla_details')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">২ ঘণ্টা আগে</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/b2.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">করোনা শনাক্তের হার ২ শতাংশের নিচে</h4>
                    <p class="text mb-0"></p>দেশে সর্বশেষ ২৪ ঘণ্টায় (গতকাল বুধবার সকাল ৮টা থেকে আজ বৃহস্পতিবার সকাল ৮টা পর্যন্ত) করোনা শনাক্ত হয়েছে ৬৯ জনের। এ সময় করোনায় কারও মৃত্যু হয়নি। আগের দিন করোনা শনাক্ত হয়েছিল ৬২ জনের। গত দিনেও কারও মৃত্যু হয়নি...</p>
                    <a href="{{url_for('news.bangla_details2')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">প্রকাশ: ১০ নভেম্বর ২০২২, ১৭: ৫৭</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">টেসলার ৪০০ কোটি ডলারের শেয়ার বেচবেন ইলন মাস্ক</h4>
                  <p class="text mb-0">টুইটারের দায়িত্ব নিয়ে বিশ্বজুড়ে হইচই ফেলে দেওয়া ইলন মাস্ক টেসলার ৪০০ কোটি মার্কিন ডলারের শেয়ার বিক্রির ঘোষণা দিয়েছেন। ব্রিটিশ গণমাধ্যম বিবিসির এক প্রতিবেদনে এ তথ্য জানানো হয়েছে...</p>
                    <a href="{{url_for('news.bangla_details_int_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">প্রকাশ: ০৯ নভেম্বর ২০২২, ১০: ২৯</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">নিগারের ঝোড়ো ফিফটি, ফারিহার হ্যাটট্রিকে মালয়েশিয়াকে পাত্তা দিল না বাংলাদেশ</h4>
                  <p class="text mb-0">ফারিহা ইসলামের সৌজন্যে মালয়েশিয়ার মেয়েদের ইনিংসের শুরুটা ভালো হয়নি। ব্যাটিং পাওয়ারপ্লেতে মাত্র ১৩ রান তুলতেই ৩ উইকেট হারান তাঁরা। ৩টিই পাওয়ারপ্লের শেষ ওভারে, টানা ৩ বলে। ফারিহার তৃতীয় ওভারের দ্বিতীয় বলটি মালয়েশিয়ার অধিনায়ক উইনিফ্রেড দুরাইসিঙ্গামের স্টাম্প ভেঙে দেয় দুর্দান্ত ইনসুইংয়ে। সুইং ছিল পরের বলেও। সেটিতেও এলবিডব্লুর শিকার নতুন ব্যাটার মাস এলিসা...</p>
                    <a href="{{url_for('news.bangla_details_s_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">প্রকাশ: ০৬ অক্টোবর ২০২২, ১৭: ৪৩</small></p>
              </div>
            </div>
    
          
        </div>
    </div>
  </div>

{% endblock %}

update_summarizer/templates/news/bangla/details2.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/bangla/details.css')}}"> {% endblock %}
{% block content %} 
{% include "main/index-b.html" %} 
<div class="row">
<div class="col-md-10 offset-md-2 mx-auto my-2">
  <h3>সারসংক্ষেপ:</h3>
  <div class="sum-body-title">
    আজ স্বাস্থ্য অধিদপ্তরের সংবাদ বিজ্ঞপ্তিতে জানানো হয়, গত ২৪ ঘণ্টায় সারা দেশে ৪ হাজার ৫২৮টি নমুনা পরীক্ষা করা হয়। পরীক্ষার বিপরীতে রোগী শনাক্তের হার ১ দশমিক ৫২ শতাংশ। আগের দিন শনাক্ত হয়েছিল ১ দশমিক ৬৬ শতাংশ।
  </div>

  <img style="height: 65vh;"
    src="{{ url_for('static', filename='images/news/bangla/b2.PNG')}}"
    class="w-60 mb-3" alt="...">

  <h1>করোনা শনাক্তের হার ২ শতাংশের নিচে</h1>
  <p class="card-text"><small class="text-muted">প্রকাশ: ১০ নভেম্বর ২০২২, ১৭: ৫৭</small></p>
  <div class="my-3">

   <p>দেশে সর্বশেষ ২৪ ঘণ্টায় (গতকাল বুধবার সকাল ৮টা থেকে আজ বৃহস্পতিবার সকাল ৮টা পর্যন্ত) করোনা শনাক্ত হয়েছে ৬৯ জনের। এ সময় করোনায় কারও মৃত্যু হয়নি। আগের দিন করোনা শনাক্ত হয়েছিল ৬২ জনের। গত দিনেও কারও মৃত্যু হয়নি।

    আজ স্বাস্থ্য অধিদপ্তরের সংবাদ বিজ্ঞপ্তিতে জানানো হয়, গত ২৪ ঘণ্টায় সারা দেশে ৪ হাজার ৫২৮টি নমুনা পরীক্ষা করা হয়। পরীক্ষার বিপরীতে রোগী শনাক্তের হার ১ দশমিক ৫২ শতাংশ। আগের দিন শনাক্ত হয়েছিল ১ দশমিক ৬৬ শতাংশ।</p>
    <p>দেশে এখন পর্যন্ত ২০ লাখ ৩৬ হাজার ৬১ জনের করোনা শনাক্ত হয়েছে। করোনা থেকে সুস্থ হয়েছেন ১৯ লাখ ৮৩ হাজার ২৫৮ জন এবং এ পর্যন্ত মারা গেছেন ২৯ হাজার ৪২৬ জন।</p>
    <p>দেশে প্রথম করোনা শনাক্ত হয় ২০২০ সালের ৮ মার্চ। এর পর থেকে এ পর্যন্ত দেশে সংক্রমণের চিত্রে কয়েক দফা ওঠানামা দেখা গেছে। গত বছরের শেষ দিক থেকে চলতি বছরের ফেব্রুয়ারির মাঝামাঝি পর্যন্ত করোনার অমিক্রন ধরনের দাপট চলে। পরে ধীরে ধীরে তা কমতে থাকে।</p>

  </div>
  <div class="my-5">
    <h3>সম্পর্কিত সংবাদ:</h3>
    <div class="mt-2">
      <div class="title-related-news mb-1">করোনা শনাক্ত ৪৮ জনের
      </div>
      <p class="text mb-0">দেশে সর্বশেষ ২৪ ঘণ্টায় (গতকাল বৃহস্পতিবার সকাল ৮টা থেকে আজ শুক্রবার সকাল ৮টা পর্যন্ত) করোনা শনাক্ত হয়েছে ৪৮ জনের। এ সময় করোনায় কারও মৃত্যু হয়নি। আগের দিন করোনা শনাক্ত হয়েছিল ৬২ জনের। গত দিনেও কারও মৃত্যু হয়নি।

        আজ স্বাস্থ্য অধিদপ্তরের সংবাদ বিজ্ঞপ্তিতে জানানো হয়, গত ২৪ ঘণ্টায় সারা দেশে ২ হাজার ৪৩৪টি নমুনা পরীক্ষা করা হয়। পরীক্ষার বিপরীতে রোগী শনাক্তের হার ১ দশমিক ৯৭ শতাংশ। আগের দিন শনাক্ত হয়েছিল ১ দশমিক ৫২ শতাংশ।
        
        দেশে এখন পর্যন্ত ২০ লাখ ৩৬ হাজার ১০৯ জনের করোনা শনাক্ত হয়েছে। করোনা থেকে সুস্থ হয়েছেন ১৯ লাখ ৮৩ হাজার ৪২৪ জন এবং এ পর্যন্ত মারা গেছেন ২৯ হাজার ৪২৬ জন।
        
        দেশে প্রথম করোনা শনাক্ত হয় ২০২০ সালের ৮ মার্চ। এর পর থেকে এ পর্যন্ত দেশে সংক্রমণের চিত্রে কয়েক দফা ওঠানামা দেখা গেছে। গত বছরের শেষ দিক থেকে চলতি বছরের ফেব্রুয়ারির মাঝামাঝি পর্যন্ত করোনার অমিক্রন ধরনের দাপট চলে। পরে ধীরে ধীরে তা কমতে থাকে।</p>
    </div>
  </div>
</div>
</div>


</div>
</div>
</div>
{% endblock %}

update_summarizer/templates/news/bangla/entertainments.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/bangla/bangla-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index-b.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-md-2 mt-2">
            <h2 style="color: #006b41;">বিনোদন</h2>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/b1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">বুয়েট ছাত্র ফারদিন কীভাবে চনপাড়া বস্তিতে, উত্তর খুঁজছে পুলিশ</h4>
                  <p class="text mb-0">বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ের (বুয়েট) শিক্ষার্থী ফারদিন নূর ওরফে পরশকে কারা কী কারণে হত্যা করেছে, তা এখনো জানা যায়নি। হত্যার সঙ্গে সরাসরি জড়িত কাউকে এখনো গ্রেপ্তার করতে পারেনি আইনশৃঙ্খলা রক্ষাকারী বাহিনী...</p>
                    <a href="{{url_for('news.bangla_details')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">২ ঘণ্টা আগে</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/b2.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">করোনা শনাক্তের হার ২ শতাংশের নিচে</h4>
                    <p class="text mb-0"></p>দেশে সর্বশেষ ২৪ ঘণ্টায় (গতকাল বুধবার সকাল ৮টা থেকে আজ বৃহস্পতিবার সকাল ৮টা পর্যন্ত) করোনা শনাক্ত হয়েছে ৬৯ জনের। এ সময় করোনায় কারও মৃত্যু হয়নি। আগের দিন করোনা শনাক্ত হয়েছিল ৬২ জনের। গত দিনেও কারও মৃত্যু হয়নি...</p>
                    <a href="{{url_for('news.bangla_details2')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">প্রকাশ: ১০ নভেম্বর ২০২২, ১৭: ৫৭</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">টেসলার ৪০০ কোটি ডলারের শেয়ার বেচবেন ইলন মাস্ক</h4>
                  <p class="text mb-0">টুইটারের দায়িত্ব নিয়ে বিশ্বজুড়ে হইচই ফেলে দেওয়া ইলন মাস্ক টেসলার ৪০০ কোটি মার্কিন ডলারের শেয়ার বিক্রির ঘোষণা দিয়েছেন। ব্রিটিশ গণমাধ্যম বিবিসির এক প্রতিবেদনে এ তথ্য জানানো হয়েছে...</p>
                    <a href="{{url_for('news.bangla_details_int_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">প্রকাশ: ০৯ নভেম্বর ২০২২, ১০: ২৯</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/bangla/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">নিগারের ঝোড়ো ফিফটি, ফারিহার হ্যাটট্রিকে মালয়েশিয়াকে পাত্তা দিল না বাংলাদেশ</h4>
                  <p class="text mb-0">ফারিহা ইসলামের সৌজন্যে মালয়েশিয়ার মেয়েদের ইনিংসের শুরুটা ভালো হয়নি। ব্যাটিং পাওয়ারপ্লেতে মাত্র ১৩ রান তুলতেই ৩ উইকেট হারান তাঁরা। ৩টিই পাওয়ারপ্লের শেষ ওভারে, টানা ৩ বলে। ফারিহার তৃতীয় ওভারের দ্বিতীয় বলটি মালয়েশিয়ার অধিনায়ক উইনিফ্রেড দুরাইসিঙ্গামের স্টাম্প ভেঙে দেয় দুর্দান্ত ইনসুইংয়ে। সুইং ছিল পরের বলেও। সেটিতেও এলবিডব্লুর শিকার নতুন ব্যাটার মাস এলিসা...</p>
                    <a href="{{url_for('news.bangla_details_s_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">বিস্তারিত...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">প্রকাশ: ০৬ অক্টোবর ২০২২, ১৭: ৪৩</small></p>
              </div>
            </div>
    
          
        </div>
    </div>
   
  </div>

{% endblock %}