update_summarizer/news/routes.py
import os
from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)

news = Blueprint("news", __name__)


@news.route("/english", methods=["GET"])
def english_news():
    return render_template("news/english/english-news.html")

@news.route("/details", methods=["GET"])
def english_details():
    return render_template("news/english/details.html")

@news.route("/details-2", methods=["GET"])
def english_details_2():
    return render_template("news/english/details-2.html")

@news.route("/international", methods=["GET"])
def international_english():
    return render_template("news/english/international.html")

@news.route("/sports_i_1", methods=["GET"])
def international_english_i_1():
    return render_template("news/english/details-i-1.html")

@news.route("/politics", methods=["GET"])
def politics_english():
    return render_template("news/english/politics.html")

@news.route("/entertainments", methods=["GET"])
def entertainments_english():
    return render_template("news/english/entertainments.html")

@news.route("/buisness", methods=["GET"])
def buisness_english():
    return render_template("news/english/buisness.html")

@news.route("/sports", methods=["GET"])
def sports_english():
    return render_template("news/english/sports.html")

@news.route("/sports_s_1", methods=["GET"])
def sports_english_s_1():
    return render_template("news/english/details-s-1.html")






@news.route("/বাংলা", methods=["GET"])
def bangla_news():
    return render_template("news/bangla/bangla-news.html")

@news.route("/bangla-details", methods=["GET"])
def bangla_details():
    return render_template("news/bangla/details.html")

@news.route("/bangla-details2", methods=["GET"])
def bangla_details2():
    return render_template("news/bangla/details2.html")

@news.route("/আন্তর্জাতিক", methods=["GET"])
def international_bangla():
    return render_template("news/bangla/international.html")

@news.route("/bangla-details-int-1", methods=["GET"])
def bangla_details_int_1():
    return render_template("news/bangla/details-int-1.html")

@news.route("/রাজনীতি", methods=["GET"])
def politics_bangla():
    return render_template("news/bangla/politics.html")

@news.route("/বিনোদন", methods=["GET"])
def entertainments_bangla():
    return render_template("news/bangla/entertainments.html")

@news.route("/ব্যবসা", methods=["GET"])
def buisness_bangla():
    return render_template("news/bangla/buisness.html")

@news.route("/খেলাধুলা", methods=["GET"])
def sports_bangla():
    return render_template("news/bangla/sports.html")

@news.route("/bangla-details-s-1", methods=["GET"])
def bangla_details_s_1():
    return render_template("news/bangla/details-s-1.html")

update_summarizer/templates/news/english/buisness.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/english/english-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-md-2 mt-2">
            <h2 style="color: #006b41;">Buisness</h2>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
                  <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
                    <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e1.PNG')}}"
                  class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">BUET student Fardin might have been killed in Dhaka: DB</h4>
                <p class="text mb-0">Additional Commissioner (Detective Branch) of DMP Mohammad Harunur Rashid has said police
                  are suspecting that Bangladesh University of Engineering and Technology (Buet) student Fardin Noor Parash
                  was killed somewhere in Dhaka....</p>
                <a href="{{url_for('news.english_details')}}" style="text-decoration: none;">
                  <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                </a>
                <p class="card-text"><small class="text-muted update-time">12 Nov 2022, 20: 48</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e2.PNG')}}"
                  class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">1 Covid-19 death in 24hrs, positivity rate 0.85%</h4>
                <p class="text mb-0">One person died from Covid-19 in 24 hours till 8 am today (November 13, 2022), said a
                  press release issued by the Directorate General of Health Services (DGHS).....</p>
                <a href="{{url_for('news.english_details_2')}}" style="text-decoration: none;">
                  <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                </a>
                <p class="card-text"><small class="text-muted update-time">Nov 13, 2022 05:02 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
                  <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
                    <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">We all look up to Stokes: Curran</h4>
                  <p class="text mb-0">Ben Stokes and Sam Curran starred as England edged Pakistan by five wickets to win the Twenty20 World Cup on Sunday and become the sport's first dual white-ball champions, holding both the 50 and 20-over titles.....</p>
                    <a href="{{url_for('news.sports_english_s_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">Sun Nov 13, 2022 06:38 PM</small></p>
              </div>
            </div>
  
          
        </div>
    </div>
  
  </div>

{% endblock %}

update_summarizer/templates/news/english/english-news.html
{% extends "layout.html" %}
{% block add_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/english/english-news.css')}}">
{% endblock %}
{% block content %}
{% include "main/index.html" %}

<div class="container form-brand">

  <div class="row">
    <div class="col-xl-8  col-md-10 offset-xl-2 offset-md-1 mt-2">
      <h2 style="color: #006b41;">Bangladesh</h2>
      <div class="d-flex news-card mt-2">
        <div class="col-md-4">
          <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e1.PNG')}}"
            class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
          <h4 class="card-title mb-1">BUET student Fardin might have been killed in Dhaka: DB</h4>
          <p class="text mb-0">Additional Commissioner (Detective Branch) of DMP Mohammad Harunur Rashid has said police
            are suspecting that Bangladesh University of Engineering and Technology (Buet) student Fardin Noor Parash
            was killed somewhere in Dhaka....</p>
          <a href="{{url_for('news.english_details')}}" style="text-decoration: none;">
            <p class="card-text"><small class="text-muted see-more">See more...</small></p>
          </a>
          <p class="card-text"><small class="text-muted update-time">12 Nov 2022, 20: 48</small></p>
        </div>
      </div>
      <div class="d-flex news-card mt-2">
        <div class="col-md-4">
          <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e2.PNG')}}"
            class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
          <h4 class="card-title mb-1">1 Covid-19 death in 24hrs, positivity rate 0.85%</h4>
          <p class="text mb-0">One person died from Covid-19 in 24 hours till 8 am today (November 13, 2022), said a
            press release issued by the Directorate General of Health Services (DGHS).....</p>
          <a href="{{url_for('news.english_details_2')}}" style="text-decoration: none;">
            <p class="card-text"><small class="text-muted see-more">See more...</small></p>
          </a>
          <p class="card-text"><small class="text-muted update-time">Nov 13, 2022 05:02 PM</small></p>
        </div>
      </div>
      <div class="d-flex news-card mt-2">
        <div class="col-md-4">
          <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
            <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
            <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
              <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                <p class="card-text"><small class="text-muted see-more">See more...</small></p>
              </a>
              <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
        </div>
      </div>
      <div class="d-flex news-card mt-2">
        <div class="col-md-4">
          <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
            <h4 class="card-title mb-1">We all look up to Stokes: Curran</h4>
            <p class="text mb-0">Ben Stokes and Sam Curran starred as England edged Pakistan by five wickets to win the Twenty20 World Cup on Sunday and become the sport's first dual white-ball champions, holding both the 50 and 20-over titles.....</p>
              <a href="{{url_for('news.sports_english_s_1')}}" style="text-decoration: none;">
                <p class="card-text"><small class="text-muted see-more">See more...</small></p>
              </a>
              <p class="card-text"><small class="text-muted update-time">Sun Nov 13, 2022 06:38 PM</small></p>
        </div>
      </div>
    </div>
    <!-- <div class="col-md-1 col-xl-2 mt-2" >
    
      <img class="mySlides" src="{{ url_for('static', filename='images/news/english/ad1.png')}}" style="width: 160px;height:550px">
      <img class="mySlides" src="{{ url_for('static', filename='images/news/english/ad2.jpg')}}" style="width: 160px;height:550px" alt="ad">
      <img class="mySlides" src="{{ url_for('static', filename='images/news/english/ad1.png')}}" style="width: 160px;height:550px" alt="ad">
    </div> -->
  </div>

</div>
<!-- <script>
  var myIndex = 0;
  carousel();
  
  function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 2000); // Change image every 2 seconds
  }
  </script> -->

{% endblock %}

update_summarizer/templates/news/english/entertainments.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/english/english-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-md-2 mt-2">
            <h2 style="color: #006b41;">Entertainments</h2>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e1.PNG')}}"
                  class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">BUET student Fardin might have been killed in Dhaka: DB</h4>
                <p class="text mb-0">Additional Commissioner (Detective Branch) of DMP Mohammad Harunur Rashid has said police
                  are suspecting that Bangladesh University of Engineering and Technology (Buet) student Fardin Noor Parash
                  was killed somewhere in Dhaka....</p>
                <a href="{{url_for('news.english_details')}}" style="text-decoration: none;">
                  <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                </a>
                <p class="card-text"><small class="text-muted update-time">12 Nov 2022, 20: 48</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e2.PNG')}}"
                  class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">1 Covid-19 death in 24hrs, positivity rate 0.85%</h4>
                <p class="text mb-0">One person died from Covid-19 in 24 hours till 8 am today (November 13, 2022), said a
                  press release issued by the Directorate General of Health Services (DGHS).....</p>
                <a href="{{url_for('news.english_details_2')}}" style="text-decoration: none;">
                  <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                </a>
                <p class="card-text"><small class="text-muted update-time">Nov 13, 2022 05:02 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
                  <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
                    <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">We all look up to Stokes: Curran</h4>
                  <p class="text mb-0">Ben Stokes and Sam Curran starred as England edged Pakistan by five wickets to win the Twenty20 World Cup on Sunday and become the sport's first dual white-ball champions, holding both the 50 and 20-over titles.....</p>
                    <a href="{{url_for('news.sports_english_s_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">Sun Nov 13, 2022 06:38 PM</small></p>
              </div>
            </div>
  
          
        </div>
    </div>
  
  </div>

{% endblock %}

update_summarizer/templates/news/english/international.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/english/english-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-md-2 mt-2">
            <h2 style="color: #006b41;">International</h2>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
                <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
                  <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e1.PNG')}}"
                class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
              <h4 class="card-title mb-1">BUET student Fardin might have been killed in Dhaka: DB</h4>
              <p class="text mb-0">Additional Commissioner (Detective Branch) of DMP Mohammad Harunur Rashid has said police
                are suspecting that Bangladesh University of Engineering and Technology (Buet) student Fardin Noor Parash
                was killed somewhere in Dhaka....</p>
              <a href="{{url_for('news.english_details')}}" style="text-decoration: none;">
                <p class="card-text"><small class="text-muted see-more">See more...</small></p>
              </a>
              <p class="card-text"><small class="text-muted update-time">12 Nov 2022, 20: 48</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e2.PNG')}}"
                class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
              <h4 class="card-title mb-1">1 Covid-19 death in 24hrs, positivity rate 0.85%</h4>
              <p class="text mb-0">One person died from Covid-19 in 24 hours till 8 am today (November 13, 2022), said a
                press release issued by the Directorate General of Health Services (DGHS).....</p>
              <a href="{{url_for('news.english_details_2')}}" style="text-decoration: none;">
                <p class="card-text"><small class="text-muted see-more">See more...</small></p>
              </a>
              <p class="card-text"><small class="text-muted update-time">Nov 13, 2022 05:02 PM</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
                <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
                  <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
            </div>
          </div>
          <div class="d-flex news-card mt-2">
            <div class="col-md-4">
              <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">We all look up to Stokes: Curran</h4>
                <p class="text mb-0">Ben Stokes and Sam Curran starred as England edged Pakistan by five wickets to win the Twenty20 World Cup on Sunday and become the sport's first dual white-ball champions, holding both the 50 and 20-over titles.....</p>
                  <a href="{{url_for('news.sports_english_s_1')}}" style="text-decoration: none;">
                    <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                  </a>
                  <p class="card-text"><small class="text-muted update-time">Sun Nov 13, 2022 06:38 PM</small></p>
            </div>
          </div>
  
          
        </div>
    </div>
   
  </div>

{% endblock %}

update_summarizer/templates/news/english/politics.html
{% extends "layout.html" %}
{% block add_styles %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/news/english/english-news.css')}}"> {% endblock %}
{% block content %}
{% include "main/index.html" %}

<div class="container form-brand">

    <div class="row">
        <div class="col-xl-8  col-md-10 offset-md-2 mt-2">
            <h2 style="color: #006b41;">Politics</h2>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e1.PNG')}}"
                  class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">BUET student Fardin might have been killed in Dhaka: DB</h4>
                <p class="text mb-0">Additional Commissioner (Detective Branch) of DMP Mohammad Harunur Rashid has said police
                  are suspecting that Bangladesh University of Engineering and Technology (Buet) student Fardin Noor Parash
                  was killed somewhere in Dhaka....</p>
                <a href="{{url_for('news.english_details')}}" style="text-decoration: none;">
                  <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                </a>
                <p class="card-text"><small class="text-muted update-time">12 Nov 2022, 20: 48</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;" src="{{ url_for('static', filename='images/news/english/e2.PNG')}}"
                  class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                <h4 class="card-title mb-1">1 Covid-19 death in 24hrs, positivity rate 0.85%</h4>
                <p class="text mb-0">One person died from Covid-19 in 24 hours till 8 am today (November 13, 2022), said a
                  press release issued by the Directorate General of Health Services (DGHS).....</p>
                <a href="{{url_for('news.english_details_2')}}" style="text-decoration: none;">
                  <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                </a>
                <p class="card-text"><small class="text-muted update-time">Nov 13, 2022 05:02 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/i1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">Twitter employees now replying on Elon Musk's tweets to voice their concerns</h4>
                  <p class="text mb-0">Elon Musk's Twitter has been a chaotic that neither its users nor its employees sought after. Two weeks to the takeover and narratives of utter chaos and unorganised workflow has started doing the rounds, or may be Twitter users were quick enough to notice.....</p>
                    <a href="{{url_for('news.international_english_i_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">13 Nov 2022, 06:42 PM</small></p>
              </div>
            </div>
            <div class="d-flex news-card mt-2">
              <div class="col-md-4">
                <img style="height: 100%;"src="{{ url_for('static', filename='images/news/english/s1.PNG')}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8 mt-1 p-2" style="margin-left: 5px;">
                  <h4 class="card-title mb-1">We all look up to Stokes: Curran</h4>
                  <p class="text mb-0">Ben Stokes and Sam Curran starred as England edged Pakistan by five wickets to win the Twenty20 World Cup on Sunday and become the sport's first dual white-ball champions, holding both the 50 and 20-over titles.....</p>
                    <a href="{{url_for('news.sports_english_s_1')}}" style="text-decoration: none;">
                      <p class="card-text"><small class="text-muted see-more">See more...</small></p>
                    </a>
                    <p class="card-text"><small class="text-muted update-time">Sun Nov 13, 2022 06:38 PM</small></p>
              </div>
            </div>
  
          
        </div>
    </div>

  </div>

{% endblock %}